version: 1.0.{build}
configuration: Release
platform:
- x86
- x64
before_build:
- cmd: nuget restore src/Bandit.sln
build:
  project: src/Bandit.sln
  verbosity: minimal
after_build:
- cmd: >-
    7z a Bandit_v%APPVEYOR_BUILD_VERSION%_i386.zip %APPVEYOR_BUILD_FOLDER%\src\Bandit\bin\x86\Release\*.exe %APPVEYOR_BUILD_FOLDER%\src\Bandit\bin\x86\Release\*.exe.config %APPVEYOR_BUILD_FOLDER%\src\Bandit\bin\x86\Release\*.dll


    7z a Bandit_v%APPVEYOR_BUILD_VERSION%_amd64.zip %APPVEYOR_BUILD_FOLDER%\src\Bandit\bin\x64\Release\*.exe %APPVEYOR_BUILD_FOLDER%\src\Bandit\bin\x64\Release\*.exe.config %APPVEYOR_BUILD_FOLDER%\src\Bandit\bin\x64\Release\*.dll
artifacts:
- path: Bandit_v$(appveyor_build_version)_i386.zip
  name: deploy
- path: Bandit_v$(appveyor_build_version)_amd64zip
  name: deploy
deploy:
- provider: GitHub
  tag: release-v$(appveyor_build_version)
  release: Bandit Release v$(appveyor_build_version)
  auth_token:
    secure: rZmLXCATPmL0i2iCF1NAWBxFSGAwR1mL4Rm5HZ0LLR6RTqIUeCSQxNOSwf/N1fsd
  repository: junimiso04/Bandit
  artifact: deploy
  draft: false
  force_update: true
- provider: GitHub
  tag: pre-release-v$(appveyor_build_version)
  release: Bandit Pre-Release v$(appveyor_build_version)
  auth_token:
    secure: rZmLXCATPmL0i2iCF1NAWBxFSGAwR1mL4Rm5HZ0LLR6RTqIUeCSQxNOSwf/N1fsd
  repository: junimiso04/Bandit
  artifact: deploy
  prerelease: true
  force_update: true
